name: CI-ARM

on:
  push:
    branches:
      - 'arm'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up env vars
        run: |
          export GO_VERSION=1.16.5
          echo "GO_VERSION=v$(sed -n 's/GO_VERSION=//p' config.base.env)" >> $GITHUB_ENV
          echo "GO111MODULE=on" >> $GITHUB_ENV
          echo "CHANGE_MINIKUBE_NONE_USER=true" >> $GITHUB_ENV
          echo "MINIKUBE_WANTUPDATENOTIFICATION=false" >> $GITHUB_ENV
          echo "MINIKUBE_WANTREPORTERRORPROMPT=false" >> $GITHUB_ENV
          echo "GO_VERSION=v$(sed -n 's/GO_VERSION=//p' config.base.env)" >> $GITHUB_ENV
          echo "DOCKER_REGISTRY=jenkins-operator" >> $GITHUB_ENV
          echo "NAME=backup" >> $GITHUB_ENV
          echo "DOCKER_ORGANIZATION=agpenton" >> $GITHUB_ENV

          echo "GOPATH=/home/runner/go" >> $GITHUB_ENV

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./backup/pvc
          platforms: linux/arm64
          push: true
          tags: agpenton/jenkins-operator-backup:latest
          build-args: GO_VERSION=1.16.5
